### ISSUE TITLE
It does not work in Firefox

### ISSUE THREAD

**Issue by pinceladasdaweb** [vojtechsebo/js-navbar-scroll#1]
Hello @vojtechsebo, i did tests with your script in Mac Firefox (version 49.0.1) and does not work. In the Chrome it works perfectly.

I think the problem is here:

https://github.com/vojtechsebo/js-navbar-scroll/blob/master/src/index.js#L47

Possible solution:

http://stackoverflow.com/questions/33253741/addeventlistener-with-mousewheel-doesnt-work-in-firefox

**Comment by vojtechsebo** [comment]
Hi @pinceladasdaweb, thx for the report. It's fixed.

`documentElem = (document.scrollingElement === undefined) ? document.documentElement : document.body`
